### ISSUE TITLE
Log of the state Done of the workload 'container' wl.0001 in presence of multiple workload partitions is not logged.

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#24]
Example with a workload with 69 partitions:

```
$ grep wl.0001 128-tasks_run-1.output 
2014:01:25 18:33:25 MainThread   troy.logger           : [INFO    ] troy default strategy : strategize workload wl.0001!
2014:01:25 18:33:25 MainThread   troy.logger           : [INFO    ] planner  expand wl: expand workload : wl.0001 : [{'hobot_0-task_0': t.0001 : {'inputs': [], 'executable': '/bin/sh', 'stdout': None, 'outputs': [], 'stdin': None, 'tag': 'hobot_0-task_0', 'working_directory': '/N/u/mturilli/AIMES/experiments_HPDC2014/single_workload/late_binding_32-512/concurrency-50/128-tasks_run-1', 'arguments': ['128-tasks_run-1-hobot_0-task_0.sh'], 'cores': 1},
2014:01:25 18:33:25 MainThread   troy.logger           : [INFO    ] TIMER expand_workload ((<troy.planner.planner.Planner object at 0x1d131790>, 'wl.0001'), {})  :   0.25 sec
2014:01:25 18:33:25 MainThread   troy.logger           : [INFO    ] TIMER derive_overlay ((<troy.planner.planner.Planner object at 0x1d131790>, 'wl.0001'), {})  :   0.12 sec
2014:01:25 18:34:23 MainThread   troy.logger           : [INFO    ] TIMER translate_workload ((<troy.workload.workload_manager.WorkloadManager object at 0x1d131710>, 'wl.0001', 'ol.0001'), {})  :   1.20 sec
```

**Comment by andre-merzky** [comment]
I think there is a conceptual mismatch of your expectations of the current logging and what you need for experiment evaluation.  The troy logging is not as much a report of state changes in troy, but rather a debugging tool which documents code paths etc.  For example (and on topic), a workload state is only logged when some entity invokes a state query, and the 'get_state' method of that workload is called.  So, if the application is not checking the workload state, then you won't see a state log message.

More importantly, the time stamps on the log messages don't identify the point of state _change_, but the point of _query_ for the state.  So, if the state query is triggered every 60 seconds, the state change may be 59 seconds old when logged.

On of the design decisions for Troy was to keep it synchronous, and to add async events only via support of async state reporting from the pilot layers.  Neither BigJob nor Sinon support async state reporting (or any real async calls) at the moment --  BigJob likely never will, Sinon's support is planned, but timeframe is unclear.  Until that support arrives, all state reporting will remain pull based, and thus with inexact timing.

Having said that, both BigJob and Sinon support some form of inspection on the pilot, and on the units, which provide some insight on their respective life cycle.  That inspection is implemented for BigJob, but not for Sinon (Sinon's inspection was not ready when I implemented this).  Further, there is not data model nor information model in Troy which would define what information are to be exposed.  In that respect, I would like to remind you and Mark to come up with a proposal on troy information flow, as planned -- I probably should open a separate ticket for this, so that it doesn't fall off the radar again.

Resolution:  I will add a couple of log messages on state change timings -- but those will have the pull limitations described above: they will only get triggered if the respective code section is somehow invoked.  In the long run, we will have to wait for async notifications on pilot layer for better state reporting, and/or need some information model within Troy to define how lower level state information are handled / communicated / exposed.

**Comment by andre-merzky** [comment]
I am not exactly sure when you'd the log message to be logged -- the above excerpt from the logs does not appear to end in a DONE workload?  If you check the state of wl.0001, isn't the state message logged?  It seems to be for me.

**Comment by mturilli** [comment]
I would like to have a log telling me when a workload has transitioned to state 'Done'. At the moment, we have it for a partition but not for a workload.

About the type and accuracy of the logging tool, thank you for the clarification. I see your point(s). I will have to familiarize much better with the TROY code base and start to understand how to report the state changes of _TROY_. I will open a similar ticket for saga-pilot because, from my experiments point of view, I do not care what layer gives me that information.
